### ISSUE TITLE
Not able to install the Git Repo

### ISSUE THREAD

**Issue by RohitJacob** [erickpece/pyfellowshipone#1]
Not available in PyPi and has no setup.py file. Really looking forward to using this since there is no other python library for F1.

Thanks,
Rohit

**Comment by erickpece** [comment]
Hi Rohit,

Thanks for reaching out.  I've stopped doing any work on this library as I don't use F1 anymore.  Also, I've been doing all new development in Node.js for some time now, so even if I did have a need to integrate with F1 again, I'd do it using Node.

If you're interested in doing any work to update and clean up this library, I'll be more than happy to give you push access.

**Comment by RohitJacob** [comment]
I'll give it a shot! :) Will fork for now and see if I make any progress.
Thanks for letting me know!
